[package]
name = "routa"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1", features = ["os-poll", "net"] }
rustls = "0.23"
rustls-pemfile = "2"
slab = "0.4"
socket2 = { version = "0.5", features = ["all"] }
webpki-roots = "0.26"
dashmap = "6"
memmap2 = "0.9"
lru = "0.12"
notify = "6"
arc-swap = "1"
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs", "use_pem"] }
subtle = "2"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
brotli = "6"

[dev-dependencies]
rcgen = "0.14"

[profile.release]
lto = true
codegen-units = 1
panic = "unwind"   # bilinçli: worker-failover panic=unwind'a dayanıyor, "abort" OLMAMALI

[lib]
name = "routa"
path = "src/lib.rs"

[[bin]]
name = "routa"
path = "src/main.rs"
